server:
  port : 8081
spring:
  datasource:
    platform: h2
    url: jdbc:h2://localhost:8080/h2
    username: sa
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    repositories:
      bootstrap-mode: lazy
    open-in-view: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: false
