server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    #url: jdbc:h2:file:./mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect